/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exo1.h"


void
message_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char * print_message_1_arg;
    char phrase[100];

        printf("Entrer une phrase:\n");
        fgets(phrase, sizeof(phrase)-1, stdin);
        print_message_1_arg=phrase;

#ifndef	DEBUG
	clnt = clnt_create (host, MESSAGE_PROG, MESSAGE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = print_message_1(&print_message_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	message_prog_1 (host);
exit (0);
}
