/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXO1_H_RPCGEN
#define _EXO1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define MESSAGE_PROG 0x20000001
#define MESSAGE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_MESSAGE 1
extern  int * print_message_1(char **, CLIENT *);
extern  int * print_message_1_svc(char **, struct svc_req *);
extern int message_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_MESSAGE 1
extern  int * print_message_1();
extern  int * print_message_1_svc();
extern int message_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXO1_H_RPCGEN */
