/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exo1.h"

int *
print_message_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	FILE * inputFile;
    inputFile = fopen("/dev/null.txt", "a+" );
    printf("Ficher à ouvrir : %s\n", "/dev/null.txt");

    /* Verification de l'ouverture du fichier null.txt */
    if (inputFile == NULL ) {
        printf( "Erreur lors de l'ouverture du fichier /dev/null.txt ! \n");
        exit(0);
    }

    /* Ecriture sur le fichier */
    fprintf(inputFile, "%s", *argp);
    printf("Ecriture faite sur le fichier ! \n");
    fclose( inputFile );

	return &result;
}
