/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "service.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
print_somme_1(param *argp,bool_t (* eachresult) ())
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_broadcast (EXO1, V1, PRINT_SOMME,
		(xdrproc_t) xdr_param, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		eachresult) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
