/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICE_H_RPCGEN
#define _SERVICE_H_RPCGEN

#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>



#ifdef __cplusplus
extern "C" {
#endif


struct param {
	int borne_inf;
	int borne_sup;
};
typedef struct param param;

#define EXO1 0x20000001
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_SOMME 1
extern  int * print_somme_1(param *argp,bool_t (* eachresult) ());
extern  int * print_somme_1_svc(param *, struct svc_req *);
extern int exo1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_SOMME 1
extern  int * print_somme_1();
extern  int * print_somme_1_svc();
extern int exo1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_param (XDR *, param*);

#else /* K&R C */
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICE_H_RPCGEN */
