/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "service.h"

int *
print_somme_1_svc(param *argp, struct svc_req *rqstp)
{
	static int  result=0;
	int somme=0;

	int i=argp->borne_inf;
    while(i<=argp->borne_sup)
    {
        somme = somme+i;
        i = i+1;
    }

    result=somme;
    printf("Result : %d\n", result);

	return &result;
}
