/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sommeur.h"


void
exo1_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	param  print_somme_1_arg;

    char buffer[1000];

    printf("lecture a\n");
    fgets(buffer, sizeof(buffer), stdin);
    int a = atoi(buffer);
    printf("lecture b\n");
    fgets(buffer, sizeof(buffer), stdin);
    int b = atoi(buffer);
    
    /* inversion des bornes si a > b */
    if(a>b)
    {
        int c=a;
        a=b;
        b=c;
    }

    /*envoie de la borne [a,b] à calculer */
    print_somme_1_arg.borne_inf=a;
    print_somme_1_arg.borne_sup=b;

#ifndef	DEBUG
	clnt = clnt_create (host, EXO1, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = print_somme_1(&print_somme_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	exo1_1 (host);
exit (0);
}
